spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: fx-rate-consumer-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jc.kafka.common"
        spring.json.value.default.type: "com.jc.kafka.common.FxRate"
    streams:
      application-id: fx-rate-streams-app
      properties:
        spring.json.trusted.packages: "com.jc.kafka.common"
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        cache.max.bytes.buffering: 0

app:
  topic:
    fx-rates:
      name: fx-rates
      partitions: 3
      replicas: 1
      retention-ms: 604800000 # 7 days
      cleanup-policy: delete
    fx-rates-compacted:
      name: fx-rates-compacted
      partitions: 3
      replicas: 1
      cleanup-policy: compact
      min-cleanable-dirty-ratio: 0.01
      segment-ms: 100
    fx-rates-statestore:
      name: fx-rates-statestore